version: '3.8'

services:
  web:
    build: .
    ports:
      - "8089:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - elk_network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: care2x
    networks:
      - elk_network

networks:
  elk_network:
    external: true
