version: '3.8'
services:
  hcpms:
    build: .
    ports:
      - "8097:80"  # Change the port here
    depends_on:
      - hcpms_db
    networks:
      - elk_network

  hcpms_db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hcpms
      MYSQL_USER: hcpmsuser
      MYSQL_PASSWORD: hchpmspassword
    networks:
      - elk_network

networks:
  elk_network:
    external: true
