# Use an official PHP image with Apache
FROM local/php-seeder-base:latest

# Install required PHP extensions
RUN docker-php-ext-install mysqli

# Copy the source code into the container
COPY . /var/www/html/

# Copy Apache configuration file
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Set working directory
WORKDIR /var/www/html/

# Set permissions
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

# Expose port 80 for the web server
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
