FROM local/php-seeder-base:latest

# Install necessary extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copy application files to the web root
COPY ./emr /var/www/html/

# Set proper permissions
RUN chown -R www-data:www-data /var/www/html

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Copy Apache config
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Copy wait-for-it.sh script
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh

# Make wait-for-it.sh executable
RUN chmod +x /usr/local/bin/wait-for-it.sh

# Restart Apache to apply changes
RUN service apache2 restart
