# Use the official PHP image as a base
FROM local/php-seeder-base:latest

# Install necessary PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Copy the application files to the web server's root directory
COPY ./covid-tms /var/www/html/

# Set proper permissions
RUN chown -R www-data:www-data /var/www/html/

# Enable Apache modules
RUN a2enmod rewrite

# Copy custom virtual host configuration
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Restart Apache to apply changes
RUN service apache2 restart

# Expose port 80
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
