version: '3.1'

services:
  hms-db:
    image: mariadb:10.5
    container_name: hms-db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: hms
      MYSQL_USER: hmsuser
      MYSQL_PASSWORD: hmsuserpassword
    volumes:
      - hms-db-data:/var/lib/mysql
    networks:
      - elk_network

  hms-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: hms-app
    ports:
      - "8081:80"
    volumes:
      - ./hospital:/var/www/html
    depends_on:
      - hms-db
    networks:
      - elk_network

volumes:
  hms-db-data:

networks:
  elk_network:
    external: true
